# NumPy

author：黄子芮
创建时间：2018/10/17

* ndarray 多维数组
有以下注意事项：所有元素必须是相同类型

ndim属性，维度个数

shape属性，各维度大小

dtype属性，数据类型

In [2]:
import numpy as np

# 生成指定维度的随机多维数据
data = np.random.rand(2, 3)
print (data)
print (type(data))

[[0.84637228 0.34988725 0.23863176]
 [0.95878432 0.65730086 0.91907971]]
<class 'numpy.ndarray'>


* ndim, shape 和 dtype 属性

In [4]:
print ('维度个数', data.ndim)
print ('各维度大小: ', data.shape)
print ('数据类型: ', data.dtype)

维度个数 2
各维度大小:  (2, 3)
数据类型:  float64


* 创建ndarray
使用np.array（collection），collection为序列型对象（list），嵌套序列（list of list）

np.zeros，np.ones,np.empty指定大小的全0或全1数组，注意第一个参数为元组 ，用来指定大小，如（2,3）；empty并不总是返回全0，有时候返回的是未初始的随机值


In [6]:
# list转换为 ndarray
l = range(10)
data = np.array(l)
print (data)
print (data.shape)
print (data.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [8]:
# 如果想要生成一个二维数组 应该怎么办呢？嵌套序列转换为ndarray
l2 = [range(10), range(10)]
data = np.array(l2)
print (data)
print (data.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)


In [9]:
# np.zeros, np.ones 和 np.empty

# np.zeros 注意里面是一个元组
zeros_arr = np.zeros((3, 4))

# np.ones
ones_arr = np.ones((2, 3))

# np.empty
empty_arr = np.empty((3, 3))

# np.empty 指定数据类型
empty_int_arr = np.empty((3, 3), int)

print (zeros_arr)
print ('-------------')
print (ones_arr)
print ('-------------')
print (empty_arr)
print ('-------------')
print (empty_int_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------
[[1. 1. 1.]
 [1. 1. 1.]]
-------------
[[8.4e-323 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 9.5e-322]
 [0.0e+000 0.0e+000 0.0e+000]]
-------------
[[1970339893 1830839393  807419168]
 [1684823084  745763951  774974830]
 [1950943754 1718182944 1936876902]]


np.arange()类似range（），注意是arange 不是arrange

In [11]:
# np.arange()
print (np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


* ndarray数据类型

dtype,类型名 + 位数 如float64，int32

转换数组类型用astype

In [12]:
zeros_float_arr = np.zeros((3, 4), dtype=np.float64)#明确指定是什么类型的数组
print (zeros_float_arr)
print (zeros_float_arr.dtype)

# astype转换数据类型
zeros_int_arr = zeros_float_arr.astype(np.int32)
print (zeros_int_arr)
print (zeros_int_arr.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


* 矢量化 (vectorization)


In [15]:
# 矢量与矢量运算
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# "元素相乘："
print (arr * arr)

# "矩阵相加："
print (arr + arr)

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]


In [19]:
# 矢量与标量运算 会把前面的数字运用在后面每个元素上
print (1/ arr)
print (2*arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 2  4  6]
 [ 8 10 12]]


* 索引与切片

一维数组的索引与python列表的索引功能类似

In [20]:
# 一维数组
arr1 = np.arange(10)
print (arr1)

print (arr1[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


![Markdown](http://i4.fuimg.com/611786/aec99a2761a27a23.png)

In [24]:
# 多维数组 
arr2 = np.arange(12).reshape(3,4)
print (arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
print (arr2[1])

print (arr2[0:2, 2:])

print (arr2[:, 1:3])

[4 5 6 7]
[[2 3]
 [6 7]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [25]:
# 条件索引 非常有用 在进行数据过滤的时候有用

# 找出 data_arr 中 2015年后的数据
data_arr = np.random.rand(3,3)
print (data_arr)

year_arr = np.array([[2000, 2001, 2000],
                     [2005, 2002, 2009],
                     [2001, 2003, 2010]])


filtered_arr = data_arr[year_arr >= 2005]
print (filtered_arr)

[[0.5017339  0.74531547 0.98379504]
 [0.11219191 0.22277618 0.13654768]
 [0.29838454 0.6831267  0.31603618]]
[0.11219191 0.13654768 0.31603618]


In [26]:
# 多个条件
filtered_arr = data_arr[(year_arr <= 2005) & (year_arr % 2 == 0)]
print (filtered_arr)

[0.5017339  0.98379504 0.22277618]


* 转置

In [30]:
arr = np.random.rand(2,3)#生成两行三列的数据
print (arr)
print (arr.transpose())

[[0.89550286 0.85589083 0.95873865]
 [0.02208564 0.59977227 0.39512278]]
[[0.89550286 0.02208564]
 [0.85589083 0.59977227]
 [0.95873865 0.39512278]]


In [28]:
arr3d = np.random.rand(2,3,4)#三维数据 两维 三列  然后纵向是四个维度
print (arr3d)
print ('----------------------')
print (arr3d.transpose((1,0,2))) # 3x2x4  高维数据上的转换

[[[0.12150847 0.21979228 0.4752694  0.52620201]
  [0.58353326 0.24471992 0.55918624 0.41670595]
  [0.51702349 0.77032297 0.42925147 0.27616898]]

 [[0.06839978 0.61355612 0.02579184 0.06169855]
  [0.81227208 0.69840711 0.25112049 0.88658149]
  [0.50509641 0.57705717 0.19761102 0.6375159 ]]]
----------------------
[[[0.12150847 0.21979228 0.4752694  0.52620201]
  [0.06839978 0.61355612 0.02579184 0.06169855]]

 [[0.58353326 0.24471992 0.55918624 0.41670595]
  [0.81227208 0.69840711 0.25112049 0.88658149]]

 [[0.51702349 0.77032297 0.42925147 0.27616898]
  [0.50509641 0.57705717 0.19761102 0.6375159 ]]]


* 通用函数

ceil，向上最接近的整数

floor，向下最接近的整数

rint，四舍五入

isnan，判断元素是否为NaN

mutiply，元素相乘

divide，元素相除

In [31]:
arr = np.random.randn(2,3)

print (arr)
print (np.ceil(arr))
print (np.floor(arr))
print (np.rint(arr))
print (np.isnan(arr))

[[-1.36713525 -1.18759362  0.12819542]
 [ 0.28799408 -0.8557765  -1.99801838]]
[[-1. -1.  1.]
 [ 1. -0. -1.]]
[[-2. -2.  0.]
 [ 0. -1. -2.]]
[[-1. -1.  0.]
 [ 0. -1. -2.]]
[[False False False]
 [False False False]]


* np.where

矢量版本的三元表达式 x if condition else y

np.where（condition ，x，y）

In [33]:
arr = np.random.randn(3,4)
print (arr)

np.where(arr > 0, 1, -1)#如果满足条件的话，输出x，如果不满足的话输出y

[[-0.267316   -0.38162152  1.04782421 -0.32111513]
 [ 1.53116215  1.19204615 -0.54990208 -0.08382776]
 [ 2.08666438 -0.88362227 -1.18381685  1.24226923]]


array([[-1, -1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1]])

*  常用的统计方法

np.mean np.sum np.max np.min np.std  np.var  np.cumsum np.cumprod

注意 多维的话要指定统计的纬度，否则默认是全部维度上做统计

In [34]:
arr = np.arange(10).reshape(5,2)#首先生成十个元素的数组 然后把它变成五行 两列
print (arr)

print (np.sum(arr))
print (np.sum(arr, axis=0))
print (np.sum(arr, axis=1))#每一行去做一个和

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
45
[20 25]
[ 1  5  9 13 17]


* np.all 和 np.any

all,全部满足条件

any，至少有一个元素满足条件

In [36]:
arr = np.random.randn(2,3)
print (arr)

print (np.any(arr > 0))
print (np.all(arr > 0))

[[-1.38851876 -1.665329    1.31793589]
 [ 0.67618975  1.26266233  0.17698858]]
True
False


* np.unique

找到唯一值 并返回 排序结果

In [38]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print (arr)
print (np.unique(arr))#把里面的唯一值拿出来

[[1 2 1]
 [2 3 4]]
[1 2 3 4]


* 文本文件的读取

In [34]:
# loadtxt
filename = './presidential_polls.csv'
data_array = np.loadtxt(filename,      # 文件名
                        delimiter=',', # 分隔符
                        dtype=str,     # 数据类型
                        usecols=(0,2,3)) # 指定读取的列索引号
print (data_array, data_array.shape)

[['cycle' 'type' 'matchup']
 ['2016' '"polls-plus"' '"Clinton vs. Trump vs. Johnson"']
 ['2016' '"polls-plus"' '"Clinton vs. Trump vs. Johnson"']
 ..., 
 ['2016' '"polls-only"' '"Clinton vs. Trump vs. Johnson"']
 ['2016' '"polls-only"' '"Clinton vs. Trump vs. Johnson"']
 ['2016' '"polls-only"' '"Clinton vs. Trump vs. Johnson"']] (10237L, 3L)


In [35]:
# loadtxt, 明确指定每列数据的类型
filename = './presidential_polls.csv'
data_array = np.loadtxt(filename,      # 文件名
                        delimiter=',', # 分隔符
                        skiprows=1,
                        dtype={'names':('cycle', 'type', 'matchup'),
                               'formats':('i4', 'S15', 'S50')},     # 数据类型
                        usecols=(0,2,3)) # 指定读取的列索引号

print (data_array, data_array.shape) # 读取的结果是一维的数组，每个元素是一个元组

[(2016, '"polls-plus"', '"Clinton vs. Trump vs. Johnson"')
 (2016, '"polls-plus"', '"Clinton vs. Trump vs. Johnson"')
 (2016, '"polls-plus"', '"Clinton vs. Trump vs. Johnson"') ...,
 (2016, '"polls-only"', '"Clinton vs. Trump vs. Johnson"')
 (2016, '"polls-only"', '"Clinton vs. Trump vs. Johnson"')
 (2016, '"polls-only"', '"Clinton vs. Trump vs. Johnson"')] (10236L,)
