## numpy与线性代数

In [69]:
#用numpy进行线性代数运算
import numpy as np
#用numpy求矩阵的逆
#1.创建一个示例矩阵，利用mat（）函数创建一个示例矩阵：
A=np.mat("2 4 6;4 2 6;10 -4 18")
A

matrix([[ 2,  4,  6],
        [ 4,  2,  6],
        [10, -4, 18]])

In [70]:
#求矩阵的逆
#利用inv（）子例程来计算逆矩阵
inverse=np.linalg.inv(A)
inverse

matrix([[-0.41666667,  0.66666667, -0.08333333],
        [ 0.08333333,  0.16666667, -0.08333333],
        [ 0.25      , -0.33333333,  0.08333333]])

In [71]:
#用矩阵乘法进行验算
A*inverse

matrix([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 8.8817842e-16, 1.0000000e+00]])

In [72]:
#用numpy解线性方程组
#创建矩阵B和数组b
B=np.mat("1 -2 1;0 2 -8;-4 5 9")
B

matrix([[ 1, -2,  1],
        [ 0,  2, -8],
        [-4,  5,  9]])

In [73]:
b=np.array([0,8,-9])
b

array([ 0,  8, -9])

In [74]:
#调用solve()函数
x=np.linalg.solve(B,b)
print("Solution",x)

Solution [29. 16.  3.]


In [75]:
#求特征值和特征向量
C=np.mat("3 -2;1 0")#计算特征值
np.linalg.eigvals(C)

array([2., 1.])

In [76]:
#利用eig（）函数取得特征值和特征向量
eigenvalues,eigenvectors=np.linalg.eig(C)
eigenvalues

array([2., 1.])

In [77]:
eigenvectors

matrix([[0.89442719, 0.70710678],
        [0.4472136 , 0.70710678]])